Now Playing Template
secture/react-native-sonora-carplay pull request #1
Opened 2023-03-16 13:01 UTC by dani-cabal

Implementation of NowPlayingTemplate push. 

Implemented pushNowPlayingTemplate method and configuration of observers.

2023-03-16 14:15 UTC, ferdeveloper approved these changes

2023-03-17 08:13 UTC, jamogon requested changes

2023-03-17 08:13 UTC, jamogon commented on src/CarPlay.ts
> +  public pushNowPlaying(): void {
I'm not sure, but the default visibility of the methods are not public?

2023-03-17 08:13 UTC, jamogon commented on src/CarPlay.ts
> +  public popToNowPlaying(): void {
Same

2023-03-17 08:22 UTC, merged